# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auto_kupis_main2.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AutoKupisWnd(object):
    def setupUi(self, AutoKupisWnd):
        AutoKupisWnd.setObjectName("AutoKupisWnd")
        AutoKupisWnd.setEnabled(True)
        AutoKupisWnd.resize(500, 470)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AutoKupisWnd.sizePolicy().hasHeightForWidth())
        AutoKupisWnd.setSizePolicy(sizePolicy)
        AutoKupisWnd.setMinimumSize(QtCore.QSize(500, 470))
        AutoKupisWnd.setMaximumSize(QtCore.QSize(500, 470))
        self.TAB_MAIN = QtWidgets.QTabWidget(AutoKupisWnd)
        self.TAB_MAIN.setEnabled(True)
        self.TAB_MAIN.setGeometry(QtCore.QRect(10, 10, 481, 431))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TAB_MAIN.sizePolicy().hasHeightForWidth())
        self.TAB_MAIN.setSizePolicy(sizePolicy)
        self.TAB_MAIN.setMinimumSize(QtCore.QSize(481, 431))
        self.TAB_MAIN.setMaximumSize(QtCore.QSize(481, 431))
        self.TAB_MAIN.setObjectName("TAB_MAIN")
        self.TAB_SETTING = QtWidgets.QWidget()
        self.TAB_SETTING.setObjectName("TAB_SETTING")
        self.groupBox = QtWidgets.QGroupBox(self.TAB_SETTING)
        self.groupBox.setGeometry(QtCore.QRect(10, 110, 451, 111))
        self.groupBox.setObjectName("groupBox")
        self.ID_EDIT = QtWidgets.QLineEdit(self.groupBox)
        self.ID_EDIT.setGeometry(QtCore.QRect(50, 50, 211, 20))
        self.ID_EDIT.setText("")
        self.ID_EDIT.setObjectName("ID_EDIT")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 351, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 50, 21, 16))
        self.label_7.setObjectName("label_7")
        self.PW_EDIT = QtWidgets.QLineEdit(self.groupBox)
        self.PW_EDIT.setGeometry(QtCore.QRect(50, 80, 211, 20))
        self.PW_EDIT.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PW_EDIT.setObjectName("PW_EDIT")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(20, 80, 21, 16))
        self.label_8.setObjectName("label_8")
        self.SET_USER = QtWidgets.QPushButton(self.groupBox)
        self.SET_USER.setGeometry(QtCore.QRect(280, 80, 75, 23))
        self.SET_USER.setObjectName("SET_USER")
        self.RESET_USER = QtWidgets.QPushButton(self.groupBox)
        self.RESET_USER.setGeometry(QtCore.QRect(360, 80, 75, 23))
        self.RESET_USER.setObjectName("RESET_USER")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 110, 351, 16))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.groupBox_2 = QtWidgets.QGroupBox(self.TAB_SETTING)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 230, 451, 51))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(10, 20, 251, 16))
        self.label_10.setObjectName("label_10")
        self.DRIVER_CHECK = QtWidgets.QPushButton(self.groupBox_2)
        self.DRIVER_CHECK.setGeometry(QtCore.QRect(290, 20, 141, 23))
        self.DRIVER_CHECK.setObjectName("DRIVER_CHECK")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(20, 40, 251, 16))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.groupBox_3 = QtWidgets.QGroupBox(self.TAB_SETTING)
        self.groupBox_3.setEnabled(False)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 290, 451, 91))
        self.groupBox_3.setObjectName("groupBox_3")
        self.timeEdit = QtWidgets.QTimeEdit(self.groupBox_3)
        self.timeEdit.setGeometry(QtCore.QRect(20, 50, 161, 22))
        self.timeEdit.setObjectName("timeEdit")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton.setGeometry(QtCore.QRect(360, 40, 82, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_2.setGeometry(QtCore.QRect(360, 60, 82, 17))
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(10, 20, 261, 16))
        self.label_13.setObjectName("label_13")
        self.label_12 = QtWidgets.QLabel(self.TAB_SETTING)
        self.label_12.setGeometry(QtCore.QRect(420, 380, 41, 16))
        self.label_12.setObjectName("label_12")
        self.groupBox_4 = QtWidgets.QGroupBox(self.TAB_SETTING)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 451, 91))
        self.groupBox_4.setObjectName("groupBox_4")
        self.STAT_1 = QtWidgets.QLabel(self.groupBox_4)
        self.STAT_1.setGeometry(QtCore.QRect(20, 20, 401, 16))
        self.STAT_1.setObjectName("STAT_1")
        self.STAT_2 = QtWidgets.QLabel(self.groupBox_4)
        self.STAT_2.setGeometry(QtCore.QRect(20, 40, 401, 16))
        self.STAT_2.setObjectName("STAT_2")
        self.STAT_3 = QtWidgets.QLabel(self.groupBox_4)
        self.STAT_3.setGeometry(QtCore.QRect(20, 60, 401, 16))
        self.STAT_3.setObjectName("STAT_3")
        self.LOGIN_TEST = QtWidgets.QPushButton(self.groupBox_4)
        self.LOGIN_TEST.setGeometry(QtCore.QRect(290, 60, 141, 23))
        self.LOGIN_TEST.setObjectName("LOGIN_TEST")
        self.TAB_MAIN.addTab(self.TAB_SETTING, "")
        self.TAB_LECTURE = QtWidgets.QWidget()
        self.TAB_LECTURE.setObjectName("TAB_LECTURE")
        self.ADD_LIST_BOX = QtWidgets.QLineEdit(self.TAB_LECTURE)
        self.ADD_LIST_BOX.setGeometry(QtCore.QRect(10, 350, 181, 20))
        self.ADD_LIST_BOX.setMaxLength(4)
        self.ADD_LIST_BOX.setObjectName("ADD_LIST_BOX")
        self.label_16 = QtWidgets.QLabel(self.TAB_LECTURE)
        self.label_16.setGeometry(QtCore.QRect(10, 380, 341, 21))
        self.label_16.setObjectName("label_16")
        self.ADD_LIST = QtWidgets.QPushButton(self.TAB_LECTURE)
        self.ADD_LIST.setGeometry(QtCore.QRect(200, 350, 71, 23))
        self.ADD_LIST.setObjectName("ADD_LIST")
        self.groupBox_5 = QtWidgets.QGroupBox(self.TAB_LECTURE)
        self.groupBox_5.setGeometry(QtCore.QRect(280, 10, 181, 121))
        self.groupBox_5.setObjectName("groupBox_5")
        self.RUN = QtWidgets.QPushButton(self.groupBox_5)
        self.RUN.setGeometry(QtCore.QRect(30, 50, 131, 23))
        self.RUN.setObjectName("RUN")
        self.RESET = QtWidgets.QPushButton(self.groupBox_5)
        self.RESET.setEnabled(False)
        self.RESET.setGeometry(QtCore.QRect(30, 80, 131, 23))
        self.RESET.setObjectName("RESET")
        self.DELAY_BOX = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.DELAY_BOX.setGeometry(QtCore.QRect(70, 20, 71, 22))
        self.DELAY_BOX.setMaximum(10.0)
        self.DELAY_BOX.setProperty("value", 0.3)
        self.DELAY_BOX.setObjectName("DELAY_BOX")
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(20, 20, 41, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setGeometry(QtCore.QRect(150, 20, 21, 21))
        self.label_18.setObjectName("label_18")
        self.groupBox_6 = QtWidgets.QGroupBox(self.TAB_LECTURE)
        self.groupBox_6.setGeometry(QtCore.QRect(280, 290, 181, 91))
        self.groupBox_6.setObjectName("groupBox_6")
        self.DELETE_LIST = QtWidgets.QPushButton(self.groupBox_6)
        self.DELETE_LIST.setGeometry(QtCore.QRect(30, 20, 131, 23))
        self.DELETE_LIST.setObjectName("DELETE_LIST")
        self.RESET_LIST = QtWidgets.QPushButton(self.groupBox_6)
        self.RESET_LIST.setGeometry(QtCore.QRect(30, 50, 131, 23))
        self.RESET_LIST.setObjectName("RESET_LIST")
        self.groupBox_7 = QtWidgets.QGroupBox(self.TAB_LECTURE)
        self.groupBox_7.setGeometry(QtCore.QRect(280, 140, 181, 141))
        self.groupBox_7.setObjectName("groupBox_7")
        self.QUIT = QtWidgets.QPushButton(self.groupBox_7)
        self.QUIT.setGeometry(QtCore.QRect(30, 100, 131, 23))
        self.QUIT.setObjectName("QUIT")
        self.HEADLESS_CHECK = QtWidgets.QRadioButton(self.groupBox_7)
        self.HEADLESS_CHECK.setGeometry(QtCore.QRect(32, 41, 82, 17))
        self.HEADLESS_CHECK.setObjectName("HEADLESS_CHECK")
        self.OPEN_AND_WAIT = QtWidgets.QPushButton(self.groupBox_7)
        self.OPEN_AND_WAIT.setGeometry(QtCore.QRect(30, 70, 131, 23))
        self.OPEN_AND_WAIT.setObjectName("OPEN_AND_WAIT")
        self.label_22 = QtWidgets.QLabel(self.groupBox_7)
        self.label_22.setGeometry(QtCore.QRect(15, 15, 151, 21))
        self.label_22.setObjectName("label_22")
        self.TARGET_LIST = QtWidgets.QListWidget(self.TAB_LECTURE)
        self.TARGET_LIST.setGeometry(QtCore.QRect(10, 11, 261, 331))
        self.TARGET_LIST.setProperty("showDropIndicator", False)
        self.TARGET_LIST.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TARGET_LIST.setObjectName("TARGET_LIST")
        self.TAB_MAIN.addTab(self.TAB_LECTURE, "")
        self.TAB_INFO = QtWidgets.QWidget()
        self.TAB_INFO.setObjectName("TAB_INFO")
        self.label = QtWidgets.QLabel(self.TAB_INFO)
        self.label.setGeometry(QtCore.QRect(10, 80, 379, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.TAB_INFO)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 210, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.TAB_INFO)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 293, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.TAB_INFO)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 164, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.TAB_INFO)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 351, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.TAB_MAIN.addTab(self.TAB_INFO, "")

        self.retranslateUi(AutoKupisWnd)
        self.TAB_MAIN.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AutoKupisWnd)

    def retranslateUi(self, AutoKupisWnd):
        _translate = QtCore.QCoreApplication.translate
        AutoKupisWnd.setWindowTitle(_translate("AutoKupisWnd", "Auto Kupis 2"))
        self.groupBox.setTitle(_translate("AutoKupisWnd", "User Information"))
        self.label_6.setText(_translate("AutoKupisWnd", "* Be sure to set your portal-homepage user ID and password first."))
        self.label_7.setText(_translate("AutoKupisWnd", "ID"))
        self.label_8.setText(_translate("AutoKupisWnd", "PW"))
        self.SET_USER.setText(_translate("AutoKupisWnd", "Set"))
        self.RESET_USER.setText(_translate("AutoKupisWnd", "Reset"))
        self.groupBox_2.setTitle(_translate("AutoKupisWnd", "System Check"))
        self.label_10.setText(_translate("AutoKupisWnd", "* Auto Kupis 2 uses Firefox as a default browser."))
        self.DRIVER_CHECK.setText(_translate("AutoKupisWnd", "Driver Check"))
        self.groupBox_3.setTitle(_translate("AutoKupisWnd", "Timer(Experimental)"))
        self.radioButton.setText(_translate("AutoKupisWnd", "Enable"))
        self.radioButton_2.setText(_translate("AutoKupisWnd", "Disable"))
        self.label_13.setText(_translate("AutoKupisWnd", "* Request will be sent right after the time set."))
        self.label_12.setText(_translate("AutoKupisWnd", "0.1.0va"))
        self.groupBox_4.setTitle(_translate("AutoKupisWnd", "Summary"))
        self.STAT_1.setText(_translate("AutoKupisWnd", "Browser status: Unknown"))
        self.STAT_2.setText(_translate("AutoKupisWnd", "User info: Unknown"))
        self.STAT_3.setText(_translate("AutoKupisWnd", "Timer: Disabled"))
        self.LOGIN_TEST.setText(_translate("AutoKupisWnd", "Login Test"))
        self.TAB_MAIN.setTabText(self.TAB_MAIN.indexOf(self.TAB_SETTING), _translate("AutoKupisWnd", "Setting"))
        self.label_16.setText(_translate("AutoKupisWnd", "* Create lecture code list. Make sure to add correctly."))
        self.ADD_LIST.setText(_translate("AutoKupisWnd", "Add"))
        self.groupBox_5.setTitle(_translate("AutoKupisWnd", "Request"))
        self.RUN.setText(_translate("AutoKupisWnd", "Run"))
        self.RESET.setText(_translate("AutoKupisWnd", "Reset"))
        self.label_17.setText(_translate("AutoKupisWnd", "Delay"))
        self.label_18.setText(_translate("AutoKupisWnd", "sec"))
        self.groupBox_6.setTitle(_translate("AutoKupisWnd", "List"))
        self.DELETE_LIST.setText(_translate("AutoKupisWnd", "Delete"))
        self.RESET_LIST.setText(_translate("AutoKupisWnd", "Reset"))
        self.groupBox_7.setTitle(_translate("AutoKupisWnd", "Browser"))
        self.QUIT.setText(_translate("AutoKupisWnd", "Quit"))
        self.HEADLESS_CHECK.setText(_translate("AutoKupisWnd", "Headless"))
        self.OPEN_AND_WAIT.setText(_translate("AutoKupisWnd", "Open and wait"))
        self.label_22.setText(_translate("AutoKupisWnd", "* Headless mode is detectable"))
        self.TAB_MAIN.setTabText(self.TAB_MAIN.indexOf(self.TAB_LECTURE), _translate("AutoKupisWnd", "Run"))
        self.label.setText(_translate("AutoKupisWnd", "You may modify and redistribute this program as long as you notify the source."))
        self.label_2.setText(_translate("AutoKupisWnd", "Copyright © 2019, acoustikue(SukJoon Oh)"))
        self.label_3.setText(_translate("AutoKupisWnd", "You can find full code in  https://github.com/dev-acoustikue, "))
        self.label_4.setText(_translate("AutoKupisWnd", "license is explicitly mentioned."))
        self.label_5.setText(_translate("AutoKupisWnd", "Auto Kupis 2, Konkuk Univ. Automatic Sugang-request-looper"))
        self.TAB_MAIN.setTabText(self.TAB_MAIN.indexOf(self.TAB_INFO), _translate("AutoKupisWnd", "Info"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AutoKupisWnd = QtWidgets.QDialog()
    ui = Ui_AutoKupisWnd()
    ui.setupUi(AutoKupisWnd)
    AutoKupisWnd.show()
    sys.exit(app.exec_())
